"""username attribute added

Revision ID: 125ac271a258
Revises: 9e7d7966646e
Create Date: 2024-08-21 16:41:09.711903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125ac271a258'
down_revision = '9e7d7966646e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
